name: release_flatpak

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  BUILD_PYTHON_VERSION: 3.8
  BUILD_POETRY_VERSION: 1.1.13

jobs:
  build_python:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Set up Poetry ${{ env.BUILD_POETRY_VERSION }}
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.BUILD_POETRY_VERSION }}

      - name: Build project for distribution
        run: poetry build

      - name: Save release python packages
        uses: actions/upload-artifact@v2
        with:
          name: release_dist_python
          path: dist

  build_flatpak:
    needs: build_python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Load release python packages
        uses: actions/download-artifact@v2
        with:
          name: release_dist_python
          path: dist

      - name: Install requirements
        run: |
          sudo apt-get install -y desktop-file-utils appstream-util

      - name: Release
        env:
          GIT_USER: vzhd1701
          GIT_EMAIL: vzhd1701@gmail.com
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          FLATPAK_GIT_REPO: vzhd1701/gridplayer-flatpak
          FLATHUB_GIT_REPO: flathub/com.vzhd1701.gridplayer
        run: |
          bash scripts/linux_meta/build.sh
          bash scripts/flatpak/build_git.sh
